[package]
name = "node-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proto = { path = "../proto" }
workload_manager_lib = { path = "./workload_manager_lib" }
tonic = "0.8"
