name: Kudo CI

on:
  push:
    branches: ["main", "project-demo-202208"]
  pull_request:
    branches: ["main", "project-demo-202208"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install clippy
        run: rustup component add clippy
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Cargo setup
        run: |
          echo "[target.x86_64-unknown-linux-gnu]" >> ~/.cargo/config
          echo "runner = 'sudo -E'" >> ~/.cargo/config
      - name: Build
        run: make kudo
      - name: Lint
        run: make lint
      - name: Format
        run: make format
      - name: Tests
        run: make check
